services:
  - type: web
    name: telegram-ai-bot
    env: python
    plan: free
    branch: main


    pythonVersion: 3.11.3 

    buildCommand: pip install -r requirements.txt
    startCommand: python main.py

    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
